### ISSUE TITLE
Autotask Compilation Issue

### ISSUE THREAD

**Issue by utahir** [BrandonBoone/Autotask.js#3]
We are not able to compile autotask.js on our side, when we try to run it using node it gives us the following error. Please guide. 

> node autotask
> module.js:327
>     throw err;
>     ^

Error: Cannot find module './templates'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Intagleo\Autotask\autotask.js:17:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by kamerynn** [comment]
@utahir Did you ever find a solution for this? Running into the same issue

**Comment by BrandonBoone** [comment]
Fixed by 2076c5e
